### PR TITLE
add missing symlinks for apps directory in 16, 22, & 24

### PR DESCRIPTION
**Pull request by lots0logs**

### CODE REVIEW

**Comment by Foggalong** [comment]
What are these for? They're not present in the Circle packaging that I can see either

**Comment by lots0logs** [comment]
They are present in highcolor. I noticed they are missing because the tray icon for an app I use stopped working since updating Square to this repo version (CopyQ).

**Comment by Foggalong** [comment]
@lots0logs The reason we took the icons out of that location from Numix Circle / Square and moved them to base is because they were causing problems there, so this could potentially reaggregate the problem. I'm not sure why CopyQ would stop working though, it doesn't have any related icons in `Numix/16/apps` :/

**Comment by lots0logs** [comment]
@Foggalong I'm not sure. You know more than me about icons, that I do know haha. All I can tell you is that the tray icon for CopyQ uses the ugly icon from highcolor ever since I updated Square. It seems like it must have something to do with the icon path. The path to the icon that is found in highcolor doesn't exist in Square nor in Numix Core.

**Comment by Foggalong** [comment]
@lots0logs Do you have this bug with Circle too?

**Comment by lots0logs** [comment]
@Foggalong Yes, I just installed the vanilla packages from the AUR (core and circle) and the issue exists with circle as well.

I think the problem is that core includes an apps directory which does not include some of the icons in Square and Circle (like CopyQ for example). So when CopyQ requests an icon that is 24px in size and is identified by the name `copyq` it has no way to find the icon in Square/Circle, Core doesn't have one, thus hicolor is used.

**_Update:**_ So after thinking about the scenario I just explained it occurred to me that the changes in this PR will not fix the problem :doh:

**Comment by lots0logs** [comment]
@Foggalong Updated the changes and tested them locally. Solves the issue :+1:

**Comment by Foggalong** [comment]
@lots0logs The way it's historically worked is that if an icon is needed in a particular size *x*, it will first look in size *x* and then if it can't be found there it'll look elsewhere. If it find it finds it in size *y* it'll just scale the needed icon from *y* to *x*. This is all managed through values set in the `index.theme` files and it's what has allowed us to develop the theme with only 48px icons, compromising on the detail lost through scaling down.

What I don't get though is why this has stopped working since Numix Core was introduced because we've not (that I'm aware) changed the `index.theme` file at all?

**Comment by Foggalong** [comment]
If I've understood the reasoning correctly, this is a wontfix issue.

**Pull request closed without merging**
