### PR TITLE
Updated Discord logo

### PR DESCRIPTION
**Pull request by MV525**
Updated Discord logo to be symmetric

### CODE REVIEW

**Comment by MV525** [comment]
The "Much cleaner SVG file" commit is for the regular Discord logo.

**Comment by Foggalong** [comment]
Please check readmes before opening, this is a packaging repo not the source! Transferred the issue to the source repo but the PR will have to be reopened manually :slightly_smiling_face:

**Comment by MV525** [comment]
I apologise for that, thank you for transferring the issue to the source repo. 🙂

**Comment by Foggalong** [comment]
No worries!

**Pull request closed without merging**
