### PR TITLE
Add arch yay installation

### PR DESCRIPTION
**Pull request by kmvan**
Add arch yay installation

### CODE REVIEW

**Comment by palob** [comment]
We've already got the link to the AUR package which however seems to be dead. As far as I can see every AUR package of Numix Circle/Square is outdated.
Does ``numix-square-icon-theme-git`` install the latest version?

We should try to get our icon themes into the community repo.

**Comment by kmvan** [comment]
The `*-git` package source is github URL. So I think that it is latest version.

**Comment by palob** [comment]
But it isn't as simple as just building from git anymore since we've split the repos into core (development) and the package repos.

**Comment by kmvan** [comment]
Emmm...
Check this: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=numix-square-icon-theme-git
Or https://aur.archlinux.org/packages/numix-square-icon-theme-git

**Comment by palob** [comment]
Why did you close this?

**Comment by kmvan** [comment]
Its not good idea because I found that the user can not get update notification when git changed.

**Pull request closed without merging**
